jobs:
  publish:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Install JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - continue-on-error: true
      name: Retrieve version
      run: 'echo "VERSION_NAME=$(cat gradle.properties | grep -w "VERSION_NAME" |
        cut -d''='' -f2)" >> $GITHUB_ENV

        '
    - continue-on-error: true
      env:
        ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_NEXUS_PASSWORD
          }}
        ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_NEXUS_USERNAME
          }}
        ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.MAVEN_SIGNING_PRIVATE_KEY
          }}
        ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.MAVEN_SIGNING_PASSWORD
          }}
      if: endsWith(env.VERSION_NAME, '-SNAPSHOT')
      name: Publish snapshot
      run: ./gradlew publish --no-daemon --no-parallel
name: Publish Snapshot
on:
  repository_dispatch:
    types: trigger-ga___publish_snapshot.yml
